# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartPhotos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'BmobSDK'
        pod 'SwiftyJSON'
	pod 'TextFieldEffects'
	pod 'NVActivityIndicatorView'
	pod 'RealmSwift'
	pod "CFNotify"
	pod 'LGButton'	
	pod 'Alamofire', '~> 5.0.0-beta.5'
	pod 'TransitionButton'
	pod 'HydraAsync'
	pod 'Kingfisher', '~> 5.0'
	pod 'Serrata'
	pod 'DeepDiff'
	pod 'SwifterSwift'
	pod 'ReachabilitySwift'
	pod "GSMessages"
	pod 'M13Checkbox'
	pod 'BEMCheckBox'
	pod 'PKHUD', '~> 5.0'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Fusuma'
	pod 'SCLAlertView'
	pod 'KDCircularProgress'
	pod "InitialsImageView"
  # Pods for SmartPhotos

end
